### PR TITLE
plat: rpi5: make scmi support optional

### PR DESCRIPTION
**Pull request by GrygiriiS**
Now ARM SCMI support is enabled for RPI5 unconditionally. This patch makes it optional and disabled by default.

### CODE REVIEW

**Comment by oleksiimoisieiev** [comment]
LGTM 
`Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by GrygiriiS** [comment]
@firscity Could we merge it if no questions, pls?

**Comment by firscity** [comment]
I'm sorry, but I don't have a required permissions.

**Comment by GrygiriiS** [comment]
As discussed SCMI kept enabled by default.

**Pull request closed without merging**
